spring:
  application:
    name: wise-office
  config:
    import: optional:file:../wise-office-infra/.env.dev[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000
  servlet:
    multipart:
      max-file-size: 5MB

jwt:
  secret: ${JWT_SECRET}
  expiration: 360000000
      
domain:
  email: all

image:
  dir: ${IMAGE_UPLOAD_DIR}
  prefix: http://localhost:${SERVER_PORT}/images/

front:
  url: ${CLIENT_URL}
  port: ${CLIENT_PORT}

#springdoc:
#  swagger-ui:
#    enabled: false
#  api-docs:
#    enabled: false

member:
  init-path: init/memberList.txt

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DOCKER_DB_URL}
  jpa:
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB

image:
  dir: /backoffice/images
  prefix: http://localhost:8080/images/

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}
  jpa:
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB

front:
  url: ${DEPLOY_SERVER_URL}
  port: 8081

domain:
  email: ${PROD_DOMAIN_EMAIL}

image:
  dir: /backoffice/images/
  prefix: ${DEPLOY_SERVER_URL}:8081/images/

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
